import type { CategoryConfig } from '@/types';

export const APPLIANCE_CATEGORIES: CategoryConfig[] = [
  {
    id: 'refrigerator',
    name: 'Heladera / Refrigerador',
    mlCategoryId: 'MLA1577',
    applianceType: 'refrigerator',
    keywords: [
      'heladera', 'refrigerador', 'frigorífico', 'nevera', 'fridge', 'refrigerator',
      'no frost', 'nofrost', 'freezer', 'combi',
    ],
    attributes: [
      { id: 'BRAND', label: 'Marca', required: true, type: 'select', options: ['Samsung', 'LG', 'Whirlpool', 'Electrolux', 'Drean', 'Philco', 'Gafa', 'Mabe', 'Candy', 'Bosch', 'Haier', 'TCL', 'Otra'] },
      { id: 'MODEL', label: 'Modelo', required: true, type: 'text', placeholder: 'Ej: RT32K5552S8' },
      { id: 'CAPACITY', label: 'Capacidad (litros)', required: true, type: 'number', unit: 'L', placeholder: 'Ej: 320' },
      { id: 'COLOR', label: 'Color', required: false, type: 'select', options: ['Blanco', 'Gris', 'Plateado', 'Negro', 'Inox', 'Otro'] },
      { id: 'VOLTAGE', label: 'Voltaje', required: false, type: 'select', options: ['220V', '110V', 'Bivolt'] },
      { id: 'COOLING_TYPE', label: 'Tipo de enfriamiento', required: false, type: 'select', options: ['No Frost', 'Frost Free', 'Frío húmedo', 'Frío seco'] },
      { id: 'ENERGY_EFFICIENCY', label: 'Eficiencia energética', required: false, type: 'select', options: ['A+++', 'A++', 'A+', 'A', 'B', 'C', 'D'] },
      { id: 'HEIGHT', label: 'Alto (cm)', required: false, type: 'number', unit: 'cm' },
      { id: 'WIDTH', label: 'Ancho (cm)', required: false, type: 'number', unit: 'cm' },
      { id: 'DEPTH', label: 'Profundidad (cm)', required: false, type: 'number', unit: 'cm' },
    ],
  },
  {
    id: 'washing_machine',
    name: 'Lavarropas',
    mlCategoryId: 'MLA1574',
    applianceType: 'washing_machine',
    keywords: [
      'lavarropas', 'lavadora', 'washing machine', 'lavasecadora', 'carga frontal', 'carga superior',
      'centrifugado', 'rpm',
    ],
    attributes: [
      { id: 'BRAND', label: 'Marca', required: true, type: 'select', options: ['Samsung', 'LG', 'Whirlpool', 'Electrolux', 'Drean', 'Candy', 'Bosch', 'Haier', 'Otra'] },
      { id: 'MODEL', label: 'Modelo', required: true, type: 'text', placeholder: 'Ej: WW80T4040CE' },
      { id: 'CAPACITY', label: 'Capacidad (kg)', required: true, type: 'number', unit: 'kg', placeholder: 'Ej: 8' },
      { id: 'TYPE', label: 'Tipo de carga', required: true, type: 'select', options: ['Carga frontal', 'Carga superior'] },
      { id: 'COLOR', label: 'Color', required: false, type: 'select', options: ['Blanco', 'Gris', 'Plateado', 'Negro', 'Otro'] },
      { id: 'VOLTAGE', label: 'Voltaje', required: false, type: 'select', options: ['220V', '110V', 'Bivolt'] },
      { id: 'ENERGY_EFFICIENCY', label: 'Eficiencia energética', required: false, type: 'select', options: ['A+++', 'A++', 'A+', 'A', 'B', 'C', 'D'] },
    ],
  },
  {
    id: 'dryer',
    name: 'Secadora',
    mlCategoryId: 'MLA4745',
    applianceType: 'dryer',
    keywords: ['secadora', 'secarropas', 'dryer', 'secado'],
    attributes: [
      { id: 'BRAND', label: 'Marca', required: true, type: 'select', options: ['Samsung', 'LG', 'Whirlpool', 'Electrolux', 'Drean', 'Otra'] },
      { id: 'MODEL', label: 'Modelo', required: true, type: 'text' },
      { id: 'CAPACITY', label: 'Capacidad (kg)', required: true, type: 'number', unit: 'kg' },
      { id: 'COLOR', label: 'Color', required: false, type: 'select', options: ['Blanco', 'Gris', 'Plateado', 'Otro'] },
      { id: 'VOLTAGE', label: 'Voltaje', required: false, type: 'select', options: ['220V', '110V', 'Bivolt'] },
    ],
  },
  {
    id: 'dishwasher',
    name: 'Lavavajillas',
    mlCategoryId: 'MLA4746',
    applianceType: 'dishwasher',
    keywords: ['lavavajillas', 'lavacopas', 'dishwasher', 'lavaplatos'],
    attributes: [
      { id: 'BRAND', label: 'Marca', required: true, type: 'select', options: ['Bosch', 'Samsung', 'LG', 'Whirlpool', 'Electrolux', 'Otra'] },
      { id: 'MODEL', label: 'Modelo', required: true, type: 'text' },
      { id: 'CAPACITY', label: 'Capacidad (cubiertos)', required: false, type: 'number', placeholder: 'Ej: 12' },
      { id: 'COLOR', label: 'Color', required: false, type: 'select', options: ['Blanco', 'Gris', 'Inox', 'Otro'] },
      { id: 'VOLTAGE', label: 'Voltaje', required: false, type: 'select', options: ['220V', '110V', 'Bivolt'] },
    ],
  },
  {
    id: 'oven',
    name: 'Horno',
    mlCategoryId: 'MLA4750',
    applianceType: 'oven',
    keywords: ['horno', 'oven', 'hornito', 'horno eléctrico', 'horno a gas', 'horno convector', 'horno conveccion'],
    attributes: [
      { id: 'BRAND', label: 'Marca', required: true, type: 'select', options: ['Broaster', 'Philips', 'Oster', 'Black+Decker', 'Electrolux', 'Whirlpool', 'Otra'] },
      { id: 'MODEL', label: 'Modelo', required: true, type: 'text' },
      { id: 'CAPACITY', label: 'Capacidad (litros)', required: false, type: 'number', unit: 'L' },
      { id: 'TYPE', label: 'Tipo', required: false, type: 'select', options: ['Eléctrico', 'Gas', 'Convector', 'Microondas+Horno'] },
      { id: 'POWER_CONSUMPTION', label: 'Potencia (watts)', required: false, type: 'number', unit: 'W' },
      { id: 'VOLTAGE', label: 'Voltaje', required: false, type: 'select', options: ['220V', '110V', 'Bivolt'] },
    ],
  },
  {
    id: 'stove',
    name: 'Cocina / Anafe',
    mlCategoryId: 'MLA4752',
    applianceType: 'stove',
    keywords: ['cocina', 'anafe', 'estufa', 'stove', 'cooktop', 'hornallas', 'vitrocerámica', 'inducción'],
    attributes: [
      { id: 'BRAND', label: 'Marca', required: true, type: 'select', options: ['Mabe', 'Longvie', 'Domec', 'Patrick', 'Whirlpool', 'Bosch', 'Otra'] },
      { id: 'MODEL', label: 'Modelo', required: true, type: 'text' },
      { id: 'TYPE', label: 'Tipo', required: false, type: 'select', options: ['Gas', 'Eléctrica', 'Inducción', 'Vitrocerámica', 'Mixta'] },
      { id: 'COLOR', label: 'Color', required: false, type: 'select', options: ['Blanco', 'Negro', 'Inox', 'Otro'] },
      { id: 'VOLTAGE', label: 'Voltaje', required: false, type: 'select', options: ['220V', '110V', 'Bivolt'] },
    ],
  },
  {
    id: 'freezer',
    name: 'Freezer',
    mlCategoryId: 'MLA4748',
    applianceType: 'freezer',
    keywords: ['freezer', 'congelador', 'deep freeze', 'conservadora'],
    attributes: [
      { id: 'BRAND', label: 'Marca', required: true, type: 'select', options: ['Samsung', 'LG', 'Whirlpool', 'Electrolux', 'Gafa', 'Philco', 'Otra'] },
      { id: 'MODEL', label: 'Modelo', required: true, type: 'text' },
      { id: 'CAPACITY', label: 'Capacidad (litros)', required: true, type: 'number', unit: 'L' },
      { id: 'TYPE', label: 'Tipo', required: false, type: 'select', options: ['Vertical', 'Horizontal', 'Cajón'] },
      { id: 'COLOR', label: 'Color', required: false, type: 'select', options: ['Blanco', 'Gris', 'Otro'] },
      { id: 'VOLTAGE', label: 'Voltaje', required: false, type: 'select', options: ['220V', '110V', 'Bivolt'] },
    ],
  },
  {
    id: 'microwave',
    name: 'Microondas',
    mlCategoryId: 'MLA4749',
    applianceType: 'microwave',
    keywords: ['microondas', 'microwave', 'horno microondas'],
    attributes: [
      { id: 'BRAND', label: 'Marca', required: true, type: 'select', options: ['Samsung', 'LG', 'Panasonic', 'Electrolux', 'Whirlpool', 'Sharp', 'Otra'] },
      { id: 'MODEL', label: 'Modelo', required: true, type: 'text' },
      { id: 'CAPACITY', label: 'Capacidad (litros)', required: false, type: 'number', unit: 'L', placeholder: 'Ej: 28' },
      { id: 'POWER_CONSUMPTION', label: 'Potencia (watts)', required: false, type: 'number', unit: 'W', placeholder: 'Ej: 1200' },
      { id: 'COLOR', label: 'Color', required: false, type: 'select', options: ['Blanco', 'Negro', 'Inox', 'Otro'] },
      { id: 'VOLTAGE', label: 'Voltaje', required: false, type: 'select', options: ['220V', '110V', 'Bivolt'] },
    ],
  },
  {
    id: 'air_fryer',
    name: 'Freidora de Aire',
    mlCategoryId: 'MLA438470',
    applianceType: 'air_fryer',
    keywords: ['freidora de aire', 'air fryer', 'airfryer', 'freidora sin aceite', 'friteuse'],
    attributes: [
      { id: 'BRAND', label: 'Marca', required: true, type: 'select', options: ['Philips', 'Tefal', 'Ninja', 'Black+Decker', 'Cosori', 'Midea', 'Otra'] },
      { id: 'MODEL', label: 'Modelo', required: true, type: 'text' },
      { id: 'CAPACITY', label: 'Capacidad (litros)', required: false, type: 'number', unit: 'L', placeholder: 'Ej: 4' },
      { id: 'POWER_CONSUMPTION', label: 'Potencia (watts)', required: false, type: 'number', unit: 'W' },
      { id: 'COLOR', label: 'Color', required: false, type: 'select', options: ['Negro', 'Blanco', 'Gris', 'Rojo', 'Otro'] },
      { id: 'VOLTAGE', label: 'Voltaje', required: false, type: 'select', options: ['220V', '110V', 'Bivolt'] },
    ],
  },
  {
    id: 'blender',
    name: 'Licuadora',
    mlCategoryId: 'MLA439005',
    applianceType: 'blender',
    keywords: ['licuadora', 'blender', 'batidora de vaso', 'procesadora', 'smoothie'],
    attributes: [
      { id: 'BRAND', label: 'Marca', required: true, type: 'select', options: ['Oster', 'Philips', 'Black+Decker', 'Hamilton Beach', 'Ninja', 'Otra'] },
      { id: 'MODEL', label: 'Modelo', required: true, type: 'text' },
      { id: 'CAPACITY', label: 'Capacidad (litros)', required: false, type: 'number', unit: 'L' },
      { id: 'POWER_CONSUMPTION', label: 'Potencia (watts)', required: false, type: 'number', unit: 'W' },
      { id: 'COLOR', label: 'Color', required: false, type: 'select', options: ['Negro', 'Blanco', 'Gris', 'Rojo', 'Otro'] },
      { id: 'VOLTAGE', label: 'Voltaje', required: false, type: 'select', options: ['220V', '110V', 'Bivolt'] },
    ],
  },
  {
    id: 'coffee_maker',
    name: 'Cafetera',
    mlCategoryId: 'MLA4753',
    applianceType: 'coffee_maker',
    keywords: ['cafetera', 'coffee maker', 'espresso', 'capsulas', 'nespresso', 'dolce gusto', 'percoladora', 'french press', 'prensa francesa'],
    attributes: [
      { id: 'BRAND', label: 'Marca', required: true, type: 'select', options: ['Nespresso', 'Dolce Gusto', 'Philips', 'Oster', 'Black+Decker', 'De Longhi', 'Otra'] },
      { id: 'MODEL', label: 'Modelo', required: true, type: 'text' },
      { id: 'TYPE', label: 'Tipo', required: false, type: 'select', options: ['Cápsulas', 'Espresso', 'Goteo', 'Prensa francesa', 'Percoladora', 'Automática'] },
      { id: 'CAPACITY', label: 'Capacidad (tazas)', required: false, type: 'number', placeholder: 'Ej: 12' },
      { id: 'POWER_CONSUMPTION', label: 'Potencia (watts)', required: false, type: 'number', unit: 'W' },
      { id: 'COLOR', label: 'Color', required: false, type: 'select', options: ['Negro', 'Blanco', 'Rojo', 'Plateado', 'Otro'] },
    ],
  },
  {
    id: 'electric_kettle',
    name: 'Pava Eléctrica',
    mlCategoryId: 'MLA5554',
    applianceType: 'electric_kettle',
    keywords: ['pava eléctrica', 'hervidor', 'kettle', 'tetera eléctrica', 'calentador de agua'],
    attributes: [
      { id: 'BRAND', label: 'Marca', required: true, type: 'select', options: ['Philips', 'Tefal', 'Black+Decker', 'Oster', 'Otra'] },
      { id: 'MODEL', label: 'Modelo', required: true, type: 'text' },
      { id: 'CAPACITY', label: 'Capacidad (litros)', required: false, type: 'number', unit: 'L', placeholder: 'Ej: 1.7' },
      { id: 'POWER_CONSUMPTION', label: 'Potencia (watts)', required: false, type: 'number', unit: 'W' },
      { id: 'COLOR', label: 'Color', required: false, type: 'select', options: ['Negro', 'Blanco', 'Plateado', 'Otro'] },
    ],
  },
  {
    id: 'vacuum_cleaner',
    name: 'Aspiradora',
    mlCategoryId: 'MLA1763',
    applianceType: 'vacuum_cleaner',
    keywords: ['aspiradora', 'vacuum', 'aspirador', 'robot aspiradora', 'escoba eléctrica', 'sin bolsa', 'ciclónica'],
    attributes: [
      { id: 'BRAND', label: 'Marca', required: true, type: 'select', options: ['Electrolux', 'Philips', 'Dyson', 'Black+Decker', 'Irobot', 'Samsung', 'Otra'] },
      { id: 'MODEL', label: 'Modelo', required: true, type: 'text' },
      { id: 'TYPE', label: 'Tipo', required: false, type: 'select', options: ['Aspiradora de pie', 'Escoba eléctrica', 'Robot aspiradora', 'Aspiradora de mano'] },
      { id: 'POWER_CONSUMPTION', label: 'Potencia (watts)', required: false, type: 'number', unit: 'W' },
      { id: 'COLOR', label: 'Color', required: false, type: 'select', options: ['Negro', 'Rojo', 'Azul', 'Gris', 'Otro'] },
      { id: 'VOLTAGE', label: 'Voltaje', required: false, type: 'select', options: ['220V', '110V', 'Bivolt'] },
    ],
  },
  {
    id: 'iron',
    name: 'Plancha',
    mlCategoryId: 'MLA4755',
    applianceType: 'iron',
    keywords: ['plancha', 'iron', 'vaporizador', 'plancha a vapor', 'centro de planchado'],
    attributes: [
      { id: 'BRAND', label: 'Marca', required: true, type: 'select', options: ['Philips', 'Tefal', 'Black+Decker', 'Rowenta', 'Otra'] },
      { id: 'MODEL', label: 'Modelo', required: true, type: 'text' },
      { id: 'TYPE', label: 'Tipo', required: false, type: 'select', options: ['A vapor', 'Seca', 'Centro de planchado'] },
      { id: 'POWER_CONSUMPTION', label: 'Potencia (watts)', required: false, type: 'number', unit: 'W' },
      { id: 'COLOR', label: 'Color', required: false, type: 'select', options: ['Negro', 'Blanco', 'Azul', 'Otro'] },
      { id: 'VOLTAGE', label: 'Voltaje', required: false, type: 'select', options: ['220V', '110V', 'Bivolt'] },
    ],
  },
  {
    id: 'toaster',
    name: 'Tostadora',
    mlCategoryId: 'MLA4756',
    applianceType: 'toaster',
    keywords: ['tostadora', 'toaster', 'tostador', 'sandwichera', 'waflera'],
    attributes: [
      { id: 'BRAND', label: 'Marca', required: true, type: 'select', options: ['Oster', 'Black+Decker', 'Philips', 'Tefal', 'Otra'] },
      { id: 'MODEL', label: 'Modelo', required: true, type: 'text' },
      { id: 'TYPE', label: 'Tipo', required: false, type: 'select', options: ['De ranura', 'Tostadora horno', 'Sandwichera', 'Waflera'] },
      { id: 'POWER_CONSUMPTION', label: 'Potencia (watts)', required: false, type: 'number', unit: 'W' },
      { id: 'COLOR', label: 'Color', required: false, type: 'select', options: ['Negro', 'Blanco', 'Plateado', 'Rojo', 'Otro'] },
    ],
  },
];

export const APPLIANCE_CATEGORIES_MAP = new Map(
  APPLIANCE_CATEGORIES.map((c) => [c.applianceType, c])
);

export function getCategoryConfig(applianceType: string): CategoryConfig | undefined {
  return APPLIANCE_CATEGORIES.find((c) => c.applianceType === applianceType);
}
